### ISSUE TITLE
About Running Storm Command

### ISSUE THREAD

**Issue by andwine** [P7h/StormTweetsSentimentD3Viz#1]
Hello,

When I run Storm command (storm jar target/storm-sentiment-viz-0.1.jar org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology SentimentAnalysis ), I encounter below error. 

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/p7h/storm/sentimentanalysis/topology/SentimentAnalysisTopology : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

My java version is 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14). 

Could you please help me out?

Thank you very much,
Best Regards,

**Comment by P7h** [comment]
You seem to be having more than one Java version installed on your machine. Though jar was created by JDK 8.x, storm is using JDK 7.x or below in your case. 
Also worth checking `storm-env.sh` in `$STORM_HOME/conf` folder if [JAVA_HOME variable](https://github.com/apache/storm/blob/master/conf/storm-env.sh#L22) is set to any other version.

**Comment by andwine** [comment]
Hello Prashanth,


Thank you very much for helping me out.

Yes, your suggestion has been working out well.  I corrected JAVA_HOME variable on storm-env.sh.


However, I encounter other issue. I think that Storm command (storm jar target/storm-sentiment-viz-0.1.jar org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology SentimentAnalysis ) need to include all library (jars) downloaded by maven.


Could you please let me know how to do it?  Otherwise, I have some kind of below errors for each jar file, which should be included.


Error: A JNI error has occurred, please check your installation and try again

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationContext

at java.lang.Class.getDeclaredMethods0(Native Method)

at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)

at java.lang.Class.privateGetMethodRecursive(Class.java:3048)

at java.lang.Class.getMethod0(Class.java:3018)

at java.lang.Class.getMethod(Class.java:1784)

at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)

at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationContext

at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

... 7 more

Thank you very much again.
Best Regards,
Sang


________________________________

**Comment by andwine** [comment]
Hello Prashanth,


If I ran storm jar command (storm jar target/storm-sentiment-viz-0.1-jar-with-dependencies.jar org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology SentimentAnalysis) with storm-sentiment-viz-0.1-jar-with-dependencies.jar, I have below error.


Exception in thread "main" java.lang.ExceptionInInitializerError

at backtype.storm.topology.TopologyBuilder.createTopology(TopologyBuilder.java:106)

at org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology.main(SentimentAnalysisTopology.java:92)

Caused by: java.lang.RuntimeException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/home/centos/StormTweetsSentimentD3Viz-master/target/storm-sentiment-viz-0.1-jar-with-dependencies.jar!/defaults.yaml, jar:file:/usr/hdp/2.2.6.0-2800/storm/lib/storm-core-0.9.3.2.2.6.0-2800.jar!/defaults.yaml]

at backtype.storm.utils.Utils.findAndReadConfigFile(Utils.java:139)

at backtype.storm.utils.Utils.readDefaultConfig(Utils.java:166)

at backtype.storm.utils.Utils.readStormConfig(Utils.java:190)

at backtype.storm.utils.Utils.<clinit>(Utils.java:77)

... 2 more

I really appreciate your help.
I look forward to hearing from you soon.
Best Regards,
Sang


________________________________

**Comment by P7h** [comment]
Please could you run the code first in local mode and check if everything is working fine. And if it works fine, then try creating the jar excluding the storm jars by making them `provided` in the `pom.xml` after this [line](https://github.com/P7h/StormTweetsSentimentD3Viz/blob/master/pom.xml#L68). You can add `<scope>provided</scope>` and give it a try.

**Comment by andwine** [comment]
Hello Prashanth,


Yes, Everything is working fine in the local mode.

For distributed mode, I followed your suggestion to exclude the storm jar. I have a strange message.


6840 [main] INFO  backtype.storm.StormSubmitter - Finished submitting topology: SentimentAnalysis

6840 [main] INFO  org.p7h.storm.sentimentanalysis.topology.SentimentAnalysisTopology -



*****Please clean your temp folder "/tmp" now!!!*****



1. Although I deleted all files and directories in /tmp, I keep having above message. Could you please inform me what I need to do?


Thank you very much,

Best Regards,

Sang

________________________________

**Comment by andwine** [comment]
Hello Prashanth,

I hope that I am not bothering you nowadays. I am very sorry for too many questions.
I think that everything is fine except nothing happens after submitting the topology.
After uploading topology jar and submitting the topology, nothing happens.
I checked Storm UI. Everything (Topology : SentimentAnalysis, Spout, Bolts, etc.) are in storm UI. I have attached a part of Storm UI.

Could you please let me know how I make sure that spout and bolts are running?

Thank you very much for your support! I really appreciate your help.
Best Regards,
Sang

________________________________

**Comment by P7h** [comment]
Hi Sang,

`*****Please clean your temp folder "/tmp" now!!!*****`
This is just a debug message displayed on the console so that its clear that a lot of temp files are being created during the Storm topology execution. This is the [line](https://github.com/P7h/StormTweetsSentimentD3Viz/blob/master/src/main/java/org/p7h/storm/sentimentanalysis/topology/SentimentAnalysisTopology.java#L84) in the code which is logging this message.
As is evident from the code, this is just a debug message and *_not_* an error message.

Regards,
Prashanth.

**Comment by andwine** [comment]
Hello Prashanth,


Thank you very much for your response.

For the distributed mode, Everything works fine now except getting message from JmsBolt to clients (html files).


1. Do I need to use <amq:connectionFactory id="jmsConnectionFactory" brokerURL="tcp://localhost:61616" /> instead of <amq:connectionFactory id="jmsConnectionFactory" brokerURL="vm://myBroker"/> in the applicationContext.xml file?


2.If so,  For "tcp://localhost:61616", what ip address should I use instead of localhost?


3. What do I need to do to configure and run ActiveMQ?


4. Is there anything I am missing?


Talk to you soon.

Best Regards,

Sang



________________________________

**Comment by andwine** [comment]
Hello Babu,


Everything is working fine now.

Thank you very much for everything.

I really appreciate your effort to help me.


Best Regards,

Sang


________________________________

**Comment by P7h** [comment]
Hi Sang,

Glad that you got it working.
Would you like to send a PR with your changes for this repo?

Regards,
Prashanth.

**Comment by andwine** [comment]
Hello Babu,


Could you please let me know what is the PR?


Thank you very much,

Best Regards,

Sang


________________________________

**Comment by P7h** [comment]
Hi Sang,

I meant Pull Request [PR].
Please check [GitHub's article](https://help.github.com/articles/using-pull-requests/) for more info on it or [this wonderful blogpost](https://yangsu.github.io/pull-request-tutorial/), which explains step-by-step process for the same.

Regards,
Prashanth.
